{
  # The filepath of the ROSbag.
  bag_path: '',

  # The topic name for the IMU.
  topic: '',

  # The number of measurements that the IMU should preintegrate before adding an IMU factor.
  imu_factor_rate: 0,

  # Plot the resulting trajectory computed from the factor graph.
  visualize_trajectory: False,

  # Prior initial pose estimate formatted as [x, y, z, roll, pitch, yaw], in m and degrees.
  prior_pose_estimate: [0, 0, 0, 0, 0, 0],
  # Prior pose standard deviations formatted as [x, y, z, roll, pitch, yaw], in m and degrees.
  prior_pose_sigmas: [0, 0, 0, 0, 0, 0],

  # Prior initial velocity formatted as [x, y, z], in m/s.
  prior_vel_estimate: [0, 0, 0],
  # Prior velocity standard deviations formatted as [x, y, z], in m/s.
  prior_vel_sigmas: [0, 0, 0],

  # Prior initial biases formatted as [accel_x, accel_y, accel_z, gyro_x, gyro_y, gyro_z],
  # in m/s^2 and degrees/s for the accelerometer and gyroscope respectively.
  prior_bias_estimate: [0, 0, 0, 0, 0, 0],
  # Prior bias standard deviations formatted as [accel_x, accel_y, accel_z, gyro_x, gyro_y, gyro_z]
  # in m/s^2 and degrees/s for the accelerometer and gyroscope respectively.
  prior_bias_sigmas: [0, 0, 0, 0, 0, 0],

  # The sensor noise standard deviation of the accelerometer formatted as [x, y, z], in m/s^2.
  accel_sigmas: [0, 0, 0],
  # The sensor noise standard deviation of the gyroscope formatted as [x, y, z], in degrees/s.
  gyro_sigmas: [0, 0, 0],
  integration_sigmas: [0, 0, 0],
}
