(cl:in-package unitree_legged_msgs-msg)
(cl:export '(LEVELFLAG-VAL
          LEVELFLAG
          COMMVERSION-VAL
          COMMVERSION
          ROBOTID-VAL
          ROBOTID
          SN-VAL
          SN
          BANDWIDTH-VAL
          BANDWIDTH
          IMU-VAL
          IMU
          MOTORSTATE-VAL
          MOTORSTATE
          FOOTFORCE-VAL
          FOOTFORCE
          FOOTFORCEEST-VAL
          FOOTFORCEEST
          TICK-VAL
          TICK
          WIRELESSREMOTE-VAL
          WIRELESSREMOTE
          RESERVE-VAL
          RESERVE
          CRC-VAL
          CRC
          EEFORCERAW-VAL
          EEFORCERAW
          EEFORCE-VAL
          EEFORCE
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          VELOCITY_W-VAL
          VELOCITY_W
))