(cl:in-package unitree_legged_msgs-msg)
(cl:export '(LEVELFLAG-VAL
          LEVELFLAG
          COMMVERSION-VAL
          COMMVERSION
          ROBOTID-VAL
          ROBOTID
          SN-VAL
          SN
          BANDWIDTH-VAL
          BANDWIDTH
          MODE-VAL
          MODE
          FORWARDSPEED-VAL
          FORWARDSPEED
          SIDESPEED-VAL
          SIDESPEED
          ROTATESPEED-VAL
          ROTATESPEED
          BODYHEIGHT-VAL
          BODYHEIGHT
          FOOTRAISEHEIGHT-VAL
          FOOTRAISEHEIGHT
          YAW-VAL
          YAW
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          LED-VAL
          LED
          WIRELESSREMOTE-VAL
          WIRELESSREMOTE
          APPREMOTE-VAL
          APPREMOTE
          RESERVE-VAL
          RESERVE
          CRC-VAL
          CRC
))