(cl:in-package unitree_legged_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LEVELFLAG-VAL
          LEVELFLAG
          COMMVERSION-VAL
          COMMVERSION
          ROBOTID-VAL
          ROBOTID
          SN-VAL
          SN
          BANDWIDTH-VAL
          BANDWIDTH
          MODE-VAL
          MODE
          IMU-VAL
          IMU
          FORWARDSPEED-VAL
          FORWARDSPEED
          SIDESPEED-VAL
          SIDESPEED
          ROTATESPEED-VAL
          ROTATESPEED
          BODYHEIGHT-VAL
          BODYHEIGHT
          UPDOWNSPEED-VAL
          UPDOWNSPEED
          FORWARDPOSITION-VAL
          FORWARDPOSITION
          SIDEPOSITION-VAL
          SIDEPOSITION
          FOOTPOSITION2BODY-VAL
          FOOTPOSITION2BODY
          FOOTSPEED2BODY-VAL
          FOOTSPEED2BODY
          FOOTFORCE-VAL
          FOOTFORCE
          FOOTFORCEEST-VAL
          FOOTFORCEEST
          TICK-VAL
          TICK
          WIRELESSREMOTE-VAL
          WIRELESSREMOTE
          RESERVE-VAL
          RESERVE
          CRC-VAL
          CRC
          EEFORCE-VAL
          EEFORCE
          JOINTP-VAL
          JOINTP
))