// Generated by gencpp from file a1_slam/FinalResults.msg
// DO NOT EDIT!


#ifndef A1_SLAM_MESSAGE_FINALRESULTS_H
#define A1_SLAM_MESSAGE_FINALRESULTS_H

#include <ros/service_traits.h>


#include <a1_slam/FinalResultsRequest.h>
#include <a1_slam/FinalResultsResponse.h>


namespace a1_slam
{

struct FinalResults
{

typedef FinalResultsRequest Request;
typedef FinalResultsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FinalResults
} // namespace a1_slam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::a1_slam::FinalResults > {
  static const char* value()
  {
    return "da3ecb06e58699211b37ea0e285d071a";
  }

  static const char* value(const ::a1_slam::FinalResults&) { return value(); }
};

template<>
struct DataType< ::a1_slam::FinalResults > {
  static const char* value()
  {
    return "a1_slam/FinalResults";
  }

  static const char* value(const ::a1_slam::FinalResults&) { return value(); }
};


// service_traits::MD5Sum< ::a1_slam::FinalResultsRequest> should match
// service_traits::MD5Sum< ::a1_slam::FinalResults >
template<>
struct MD5Sum< ::a1_slam::FinalResultsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::a1_slam::FinalResults >::value();
  }
  static const char* value(const ::a1_slam::FinalResultsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::a1_slam::FinalResultsRequest> should match
// service_traits::DataType< ::a1_slam::FinalResults >
template<>
struct DataType< ::a1_slam::FinalResultsRequest>
{
  static const char* value()
  {
    return DataType< ::a1_slam::FinalResults >::value();
  }
  static const char* value(const ::a1_slam::FinalResultsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::a1_slam::FinalResultsResponse> should match
// service_traits::MD5Sum< ::a1_slam::FinalResults >
template<>
struct MD5Sum< ::a1_slam::FinalResultsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::a1_slam::FinalResults >::value();
  }
  static const char* value(const ::a1_slam::FinalResultsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::a1_slam::FinalResultsResponse> should match
// service_traits::DataType< ::a1_slam::FinalResults >
template<>
struct DataType< ::a1_slam::FinalResultsResponse>
{
  static const char* value()
  {
    return DataType< ::a1_slam::FinalResults >::value();
  }
  static const char* value(const ::a1_slam::FinalResultsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // A1_SLAM_MESSAGE_FINALRESULTS_H
