// Generated by gencpp from file a1_slam/FinalResultsResponse.msg
// DO NOT EDIT!


#ifndef A1_SLAM_MESSAGE_FINALRESULTSRESPONSE_H
#define A1_SLAM_MESSAGE_FINALRESULTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace a1_slam
{
template <class ContainerAllocator>
struct FinalResultsResponse_
{
  typedef FinalResultsResponse_<ContainerAllocator> Type;

  FinalResultsResponse_()
    : results()  {
    }
  FinalResultsResponse_(const ContainerAllocator& _alloc)
    : results(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _results_type;
  _results_type results;





  typedef boost::shared_ptr< ::a1_slam::FinalResultsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::a1_slam::FinalResultsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FinalResultsResponse_

typedef ::a1_slam::FinalResultsResponse_<std::allocator<void> > FinalResultsResponse;

typedef boost::shared_ptr< ::a1_slam::FinalResultsResponse > FinalResultsResponsePtr;
typedef boost::shared_ptr< ::a1_slam::FinalResultsResponse const> FinalResultsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::a1_slam::FinalResultsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::a1_slam::FinalResultsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::a1_slam::FinalResultsResponse_<ContainerAllocator1> & lhs, const ::a1_slam::FinalResultsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.results == rhs.results;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::a1_slam::FinalResultsResponse_<ContainerAllocator1> & lhs, const ::a1_slam::FinalResultsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace a1_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::a1_slam::FinalResultsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a1_slam::FinalResultsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::a1_slam::FinalResultsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::a1_slam::FinalResultsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a1_slam::FinalResultsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a1_slam::FinalResultsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::a1_slam::FinalResultsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "050d718085d2969bac3160f48f51460c";
  }

  static const char* value(const ::a1_slam::FinalResultsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x050d718085d2969bULL;
  static const uint64_t static_value2 = 0xac3160f48f51460cULL;
};

template<class ContainerAllocator>
struct DataType< ::a1_slam::FinalResultsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1_slam/FinalResultsResponse";
  }

  static const char* value(const ::a1_slam::FinalResultsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::a1_slam::FinalResultsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string results\n"
;
  }

  static const char* value(const ::a1_slam::FinalResultsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::a1_slam::FinalResultsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.results);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FinalResultsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::a1_slam::FinalResultsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::a1_slam::FinalResultsResponse_<ContainerAllocator>& v)
  {
    s << indent << "results: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.results);
  }
};

} // namespace message_operations
} // namespace ros

#endif // A1_SLAM_MESSAGE_FINALRESULTSRESPONSE_H
