// Generated by gencpp from file a1_slam/GtsamResultsResponse.msg
// DO NOT EDIT!


#ifndef A1_SLAM_MESSAGE_GTSAMRESULTSRESPONSE_H
#define A1_SLAM_MESSAGE_GTSAMRESULTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace a1_slam
{
template <class ContainerAllocator>
struct GtsamResultsResponse_
{
  typedef GtsamResultsResponse_<ContainerAllocator> Type;

  GtsamResultsResponse_()
    : str()  {
    }
  GtsamResultsResponse_(const ContainerAllocator& _alloc)
    : str(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _str_type;
  _str_type str;





  typedef boost::shared_ptr< ::a1_slam::GtsamResultsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::a1_slam::GtsamResultsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GtsamResultsResponse_

typedef ::a1_slam::GtsamResultsResponse_<std::allocator<void> > GtsamResultsResponse;

typedef boost::shared_ptr< ::a1_slam::GtsamResultsResponse > GtsamResultsResponsePtr;
typedef boost::shared_ptr< ::a1_slam::GtsamResultsResponse const> GtsamResultsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::a1_slam::GtsamResultsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::a1_slam::GtsamResultsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::a1_slam::GtsamResultsResponse_<ContainerAllocator1> & lhs, const ::a1_slam::GtsamResultsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.str == rhs.str;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::a1_slam::GtsamResultsResponse_<ContainerAllocator1> & lhs, const ::a1_slam::GtsamResultsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace a1_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::a1_slam::GtsamResultsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a1_slam::GtsamResultsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::a1_slam::GtsamResultsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::a1_slam::GtsamResultsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a1_slam::GtsamResultsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a1_slam::GtsamResultsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::a1_slam::GtsamResultsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "994972b6e03928b2476860ce6c4c8e17";
  }

  static const char* value(const ::a1_slam::GtsamResultsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x994972b6e03928b2ULL;
  static const uint64_t static_value2 = 0x476860ce6c4c8e17ULL;
};

template<class ContainerAllocator>
struct DataType< ::a1_slam::GtsamResultsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1_slam/GtsamResultsResponse";
  }

  static const char* value(const ::a1_slam::GtsamResultsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::a1_slam::GtsamResultsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string str\n"
;
  }

  static const char* value(const ::a1_slam::GtsamResultsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::a1_slam::GtsamResultsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GtsamResultsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::a1_slam::GtsamResultsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::a1_slam::GtsamResultsResponse_<ContainerAllocator>& v)
  {
    s << indent << "str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // A1_SLAM_MESSAGE_GTSAMRESULTSRESPONSE_H
