// Generated by gencpp from file a1_slam/GtsamResults.msg
// DO NOT EDIT!


#ifndef A1_SLAM_MESSAGE_GTSAMRESULTS_H
#define A1_SLAM_MESSAGE_GTSAMRESULTS_H

#include <ros/service_traits.h>


#include <a1_slam/GtsamResultsRequest.h>
#include <a1_slam/GtsamResultsResponse.h>


namespace a1_slam
{

struct GtsamResults
{

typedef GtsamResultsRequest Request;
typedef GtsamResultsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GtsamResults
} // namespace a1_slam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::a1_slam::GtsamResults > {
  static const char* value()
  {
    return "0e35ec748ec070bc1eff3fd9921a52fc";
  }

  static const char* value(const ::a1_slam::GtsamResults&) { return value(); }
};

template<>
struct DataType< ::a1_slam::GtsamResults > {
  static const char* value()
  {
    return "a1_slam/GtsamResults";
  }

  static const char* value(const ::a1_slam::GtsamResults&) { return value(); }
};


// service_traits::MD5Sum< ::a1_slam::GtsamResultsRequest> should match
// service_traits::MD5Sum< ::a1_slam::GtsamResults >
template<>
struct MD5Sum< ::a1_slam::GtsamResultsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::a1_slam::GtsamResults >::value();
  }
  static const char* value(const ::a1_slam::GtsamResultsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::a1_slam::GtsamResultsRequest> should match
// service_traits::DataType< ::a1_slam::GtsamResults >
template<>
struct DataType< ::a1_slam::GtsamResultsRequest>
{
  static const char* value()
  {
    return DataType< ::a1_slam::GtsamResults >::value();
  }
  static const char* value(const ::a1_slam::GtsamResultsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::a1_slam::GtsamResultsResponse> should match
// service_traits::MD5Sum< ::a1_slam::GtsamResults >
template<>
struct MD5Sum< ::a1_slam::GtsamResultsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::a1_slam::GtsamResults >::value();
  }
  static const char* value(const ::a1_slam::GtsamResultsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::a1_slam::GtsamResultsResponse> should match
// service_traits::DataType< ::a1_slam::GtsamResults >
template<>
struct DataType< ::a1_slam::GtsamResultsResponse>
{
  static const char* value()
  {
    return DataType< ::a1_slam::GtsamResults >::value();
  }
  static const char* value(const ::a1_slam::GtsamResultsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // A1_SLAM_MESSAGE_GTSAMRESULTS_H
